const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("companion", {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  sendChat: (text) => ipcRenderer.invoke("chat:send", text),
  observeDesktop: () => ipcRenderer.invoke("chat:observeDesktop"),
  captureDesktop: () => ipcRenderer.invoke("desktop:capture"),
  getWindowPosition: () => ipcRenderer.invoke("window:getPosition"),
  setWindowPosition: (x, y) => ipcRenderer.invoke("window:setPosition", x, y),
  saveWindowPosition: () => ipcRenderer.invoke("window:savePosition"),
  setWindowMode: (mode) => ipcRenderer.invoke("window:setMode", mode),
  setWindowShape: (rects) => ipcRenderer.invoke("window:setShape", rects),
  setMousePassThrough: (enabled) => ipcRenderer.invoke("window:setMousePassThrough", enabled),
  quitApp: () => ipcRenderer.invoke("app:quit"),
  listMessages: () => ipcRenderer.invoke("messages:list"),
  resetChatAndMemory: () => ipcRenderer.invoke("data:resetChatAndMemory"),
  listMemories: () => ipcRenderer.invoke("memories:list"),
  updateMemory: (memory) => ipcRenderer.invoke("memory:update", memory),
  deleteMemory: (id) => ipcRenderer.invoke("memory:delete", id),
  createTodo: (content) => ipcRenderer.invoke("todo:create", content),
  listTodos: () => ipcRenderer.invoke("todo:list"),
  toggleTodo: (id, completed) => ipcRenderer.invoke("todo:toggle", id, completed),
  deleteTodo: (id) => ipcRenderer.invoke("todo:delete", id),
  createReminder: (text) => ipcRenderer.invoke("reminder:create", text),
  listReminders: () => ipcRenderer.invoke("reminder:list"),
  deleteReminder: (id) => ipcRenderer.invoke("reminder:delete", id),
  listLaunchItems: () => ipcRenderer.invoke("launch:list"),
  createLaunchItem: (item) => ipcRenderer.invoke("launch:create", item),
  deleteLaunchItem: (id) => ipcRenderer.invoke("launch:delete", id),
  openLaunchItem: (id) => ipcRenderer.invoke("tool:openLaunchItem", id),
  onOpenSettings: (callback) => ipcRenderer.on("ui:openSettings", callback),
  onOpenFull: (callback) => ipcRenderer.on("ui:openFull", callback),
  onShowMiniReply: (callback) => ipcRenderer.on("ui:showMiniReply", callback),
  onHideMiniReply: (callback) => ipcRenderer.on("ui:hideMiniReply", callback),
  onError: (callback) => ipcRenderer.on("ui:error", (_event, message) => callback(message)),
  onReminderDue: (callback) => ipcRenderer.on("reminder:due", (_event, reminder) => callback(reminder)),
});
